# Generated by Django 2.2.5 on 2019-10-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20191014_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app01.Tag'),
        ),
    ]
